version: '3.1'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inventory-db